
loggin:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG

spring:
  data:
    mongodb:
      #uri:'mongodb://localhost:27017/invoice_db'
      #uri: 'mongodb+srv://miirbri1:Mounir15429@ms-invoice.m6naiks.mongodb.net/?retryWrites=true&w=majority'